### ISSUE TITLE
feature request: enable adding reactions

### ISSUE THREAD

**Issue by kolharsam** [beerose/use-comments#6]
along with the current support for text-based comments, we could also potentially support reactions like shown here (image based on Disqus)

![image](https://user-images.githubusercontent.com/6604943/123386040-d9827580-d5b3-11eb-8494-1236db92f808.png)

to begin with, it can be made common for each unique post(and can be enabled at users' discretion) and eventually we could add support for reactions to other comments as well.

I could also try my hand in implementing this.

**Comment by beerose** [comment]
Hey, thanks for the feedback. I was thinking about it, and I have some ideas about it, but I'm not sure it will be a part of this library. You can check out https://www.commont.app/, a hosted version of this project, where I plan to add it soon.
